# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from delay_service.proto import delay_service_pb2 as delay__service_dot_proto_dot_delay__service__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in delay_service/proto/delay_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DelayPredictionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/delay_service.v1.DelayPredictionService/Predict',
                request_serializer=delay__service_dot_proto_dot_delay__service__pb2.PredictRequest.SerializeToString,
                response_deserializer=delay__service_dot_proto_dot_delay__service__pb2.PredictionResponse.FromString,
                _registered_method=True)
        self.PredictBatch = channel.unary_unary(
                '/delay_service.v1.DelayPredictionService/PredictBatch',
                request_serializer=delay__service_dot_proto_dot_delay__service__pb2.BatchPredictRequest.SerializeToString,
                response_deserializer=delay__service_dot_proto_dot_delay__service__pb2.BatchPredictionResponse.FromString,
                _registered_method=True)


class DelayPredictionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DelayPredictionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=delay__service_dot_proto_dot_delay__service__pb2.PredictRequest.FromString,
                    response_serializer=delay__service_dot_proto_dot_delay__service__pb2.PredictionResponse.SerializeToString,
            ),
            'PredictBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictBatch,
                    request_deserializer=delay__service_dot_proto_dot_delay__service__pb2.BatchPredictRequest.FromString,
                    response_serializer=delay__service_dot_proto_dot_delay__service__pb2.BatchPredictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'delay_service.v1.DelayPredictionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('delay_service.v1.DelayPredictionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DelayPredictionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/delay_service.v1.DelayPredictionService/Predict',
            delay__service_dot_proto_dot_delay__service__pb2.PredictRequest.SerializeToString,
            delay__service_dot_proto_dot_delay__service__pb2.PredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/delay_service.v1.DelayPredictionService/PredictBatch',
            delay__service_dot_proto_dot_delay__service__pb2.BatchPredictRequest.SerializeToString,
            delay__service_dot_proto_dot_delay__service__pb2.BatchPredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
