import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import type { IncidentHistoryPage as HistoryPage } from '../api/types'
import { IncidentCard } from '../components/IncidentCard'
import { routeDisplayName, stopDisplayName } from '../domain/vehiclePresentation'
import { useLiveMap } from '../live/liveMapContext'
import { formatIncidentDate, formatIncidentDelay } from '../domain/incidentPresentation'

export function IncidentHistoryPage() {
  const { catalog } = useLiveMap(); const navigate = useNavigate(); const { incidentId } = useParams(); const [outcome, setOutcome] = useState<'all' | 'occurred' | 'not_occurred'>('all'); const [offset, setOffset] = useState(0); const [page, setPage] = useState<HistoryPage>({ items: [], total: 0, limit: 50, offset: 0 })
  useEffect(() => { let mounted = true; fetch(`/api/v1/incidents/history?outcome=${outcome}&limit=50&offset=${offset}`).then((r) => r.json() as Promise<HistoryPage>).then((value) => { if (mounted) setPage(value) }); return () => { mounted = false } }, [offset, outcome])
  const routes = useMemo(() => new Map(catalog?.routes.map((route) => [route.id, route]) ?? []), [catalog])
  return <main className="incidents-page"><header className="incidents-heading"><div><h1>История инцидентов</h1><p>Инциденты, для которых известно фактическое прибытие.</p></div><div><strong>{page.total}</strong><span>завершено</span></div></header><section className="incidents-filters"><label>Результат<select aria-label="Фильтр результата" value={outcome} onChange={(e) => { setOutcome(e.target.value as typeof outcome); setOffset(0) }}><option value="all">Все</option><option value="occurred">Сбылись</option><option value="not_occurred">Не сбылись</option></select></label></section>
    <div className="incidents-table-wrap"><table className="incidents-table"><thead><tr><th>Результат</th><th>Транспорт</th><th>Маршрут</th><th>Остановка</th><th>Прогноз</th><th>Факт</th><th>Ошибка прогноза</th><th>Завершён</th></tr></thead><tbody>{page.items.map((incident) => <tr key={incident.id} onClick={() => navigate(`/incidents/history/${incident.id}`)}><td><strong>{incident.outcome === 'occurred' ? 'Сбылся' : 'Не сбылся'}</strong></td><td>ТС {incident.unitId}</td><td>{routeDisplayName(routes.get(incident.routePatternId))}</td><td>{stopDisplayName(incident.targetStop)}</td><td>{formatIncidentDelay(incident.predictedDelaySeconds)}</td><td>{formatIncidentDelay(incident.actualDelaySeconds)}</td><td>{formatIncidentDelay(incident.actualDelaySeconds === undefined ? undefined : incident.actualDelaySeconds - incident.predictedDelaySeconds)}</td><td>{formatIncidentDate(incident.updatedAt)}</td></tr>)}</tbody></table>{page.items.length === 0 ? <div className="incidents-empty"><strong>История пока пуста</strong></div> : null}</div>
    <div className="history-pagination"><button disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 50))}>Назад</button><span>{page.total ? `${offset + 1}–${Math.min(offset + 50, page.total)} из ${page.total}` : '0 записей'}</span><button disabled={offset + 50 >= page.total} onClick={() => setOffset(offset + 50)}>Далее</button></div>{incidentId ? <IncidentCard incidentId={incidentId} fallback={page.items.find((item) => item.id === incidentId)} onClose={() => navigate('/incidents/history')} /> : null}</main>
}
